version: 2
updates:
  - package-ecosystem: "nuget"
    directories: ["/"]
    schedule:
      interval: "monthly"
    groups:
      minor-patch:
        patterns: ["*"]
        update-types: ["minor", "patch"]
      major:
        patterns: ["*"]
        update-types: ["major"]
      security:
        applies-to: security-updates
        patterns: ["*"]

  - package-ecosystem: "npm"
    directories: ["/app"]
    schedule:
      interval: "monthly"
    groups:
      minor-patch:
        patterns: ["*"]
        update-types: ["minor", "patch"]
      major:
        patterns: ["*"]
        update-types: ["major"]
      security:
        applies-to: security-updates
        patterns: ["*"]

  - package-ecosystem: "github-actions"
    directories: ["/"]
    schedule:
      interval: "monthly"
    groups:
      minor-patch:
        patterns: ["*"]
        update-types: ["minor", "patch"]
      major:
        patterns: ["*"]
        update-types: ["major"]
      security:
        applies-to: security-updates
        patterns: ["*"]
