version: '3.4'

services:
  expensesplitter-api:
    image: ${DOCKER_REGISTRY-}expensesplitter-api
    container_name: expensesplitter-api
    build:
      context: src
      dockerfile: ExpenseSplitter.Api.Presentation/Dockerfile
    depends_on:
      - expensesplitter-db

  expensesplitter-db:
    image: postgres:latest
    container_name: expensesplitter-db
    environment:
      - POSTGRES_DB=expensesplitter
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    volumes:
      - ./.containers/expensesplitter-db:/var/lib/postgresql/data
    ports:
      - 5432:5432