version: '3.4'

services:
  expensesplitter-api:
    image: ${DOCKER_REGISTRY-}expensesplitter-api
    container_name: expensesplitter-api
    build:
      context: api/src
      dockerfile: ExpenseSplitter.Api.Presentation/Dockerfile
    depends_on:
      - expensesplitter-db
      - expensesplitter-idp
      - expensesplitter-cache

  expensesplitter-db:
    image: postgres:latest
    container_name: expensesplitter-db
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ./.containers/expensesplitter-db:/var/lib/postgresql/data
    ports:
      - 5432:5432

  expensesplitter-idp:
    image: quay.io/keycloak/keycloak:26.0 # sleighzy/keycloak:16.1.0-arm64
    command: ["start-dev", "--import-realm"]
    container_name: expensesplitter-idp
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=${KEYCLOAK_ADMIN_USERNAME}
      - KC_BOOTSTRAP_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD}
    volumes:
      - ./.containers/expensesplitter-idp:/opt/jboss/keycloak/standalone/data
      - ./.files/expensesplitter-idp-realm-export.json:/opt/keycloak/data/import/realm.json:ro
    ports:
      - 18080:8080

  expensesplitter-cache:
    image: redis:7.4.1-alpine
    container_name: expensesplitter-cache
    volumes:
      - ./.containers/expensesplitter-cache:/data
    ports:
      - 6379:6379