version: '3.4'

services:
  expensesplitter-api:
    image: ${DOCKER_REGISTRY-}expensesplitter-api
    container_name: expensesplitter-api
    build:
      context: src
      dockerfile: ExpenseSplitter.Api.Presentation/Dockerfile
    depends_on:
      - expensesplitter-db
      - expensesplitter-idp

  expensesplitter-db:
    image: postgres:latest
    container_name: expensesplitter-db
    environment:
      - POSTGRES_DB=expensesplitter
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    volumes:
      - ./.containers/expensesplitter-db:/var/lib/postgresql/data
    ports:
      - 5432:5432

  expensesplitter-idp:
    image: jboss/keycloak:latest
    container_name: expensesplitter-idp
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - KEYCLOAK_IMPORT=/tmp/expensesplitter-idp-realm-export.json
      - JGROUPS_DISCOVERY_PROTOCOL=TCPPING
      - JGROUPS_DISCOVERY_PROPERTIES=initial_hosts="localhost[7600]"
    volumes:
      - ./.containers/expensesplitter-idp:/opt/jboss/keycloak/standalone/data
      - ./.files/expensesplitter-idp-realm-export.json:/tmp/expensesplitter-idp-realm-export.json
    ports:
      - 18080:8080
