# @name login
POST {{baseUrl}}/api/v1/users/login
Content-Type: application/json

{
    "email": "user2@example.com",
    "password": "user2"
}

###

# @name listSettlements
GET {{baseUrl}}/api/v1/settlements
?page=1
&pageSize=10
Authorization: Bearer {{login.response.body.accessToken}}

###

# @name listSettlementsWithCursorInitial
GET {{baseUrl}}/api/v1/settlements/cursor
?cursor=
&limit=1
Authorization: Bearer {{login.response.body.accessToken}}

###

# @name listSettlementsWithCursor
GET {{baseUrl}}/api/v1/settlements/cursor
?cursor={{listSettlementsWithCursorInitial.response.body.nextCursor}}
&limit=1
Authorization: Bearer {{login.response.body.accessToken}}

###

# @name createSettlement
POST {{baseUrl}}/api/v1/settlements
Authorization: Bearer {{login.response.body.accessToken}}
Content-Type: application/json

{
    "name": "Weekend tripos",
    "participantNames": [
        "Agata",
        "Blazej"
    ]
}

### 

# @name getSettlement
GET {{baseUrl}}/api/v1/settlements/{{createSettlement.response.body.$}}
Authorization: Bearer {{login.response.body.accessToken}}


### 

# @name updateSettlement
PUT {{baseUrl}}/api/v1/settlements/{{createSettlement.response.body.$}}
Authorization: Bearer {{login.response.body.accessToken}}
Content-Type: application/json

{
    "name": "Updated settlement",
    "participants": [
        {
            "id": "{{getSettlement.response.body.participants[0].id}}",
            "nickname": "Updated Agata"
        },
        {
            "id": "{{getSettlement.response.body.participants[1].id}}",
            "nickname": "Updated Blazej"
        },
        {
            "nickname": "New participant"
        }
    ]
}

###

# @name deleteSettlement
DELETE {{baseUrl}}/api/v1/settlements/{{createSettlement.response.body.$}}
Authorization: Bearer {{login.response.body.accessToken}}

###

# @name deleteSettlementWithIfMatchHeader
DELETE {{baseUrl}}/api/v1/settlements/{{createSettlement.response.body.$}}
Authorization: Bearer {{login.response.body.accessToken}}
If-Match: {{getSettlement.response.headers.ETag}}

### 

# @name joinSettlement
POST {{baseUrl}}/api/v1/settlements/join
Authorization: Bearer {{login.response.body.accessToken}}
Content-Type: application/json

{
    "inviteCode": "{{getSettlement.response.body.inviteCode}}"
}

###

# @name leaveSettlement
POST {{baseUrl}}/api/v1/settlements/{{createSettlement.response.body.$}}/leave
Authorization: Bearer {{login.response.body.accessToken}}


###

# @name claimParticipant
PATCH {{baseUrl}}/api/v1/settlements/{{createSettlement.response.body.$}}/participants/{{getSettlement.response.body.participants[0].id}}/claim
Authorization: Bearer {{login.response.body.accessToken}}

###

# @name createExpense
POST {{baseUrl}}/api/v1/expenses
Authorization: Bearer {{login.response.body.accessToken}}
Content-Type: application/json

{
    "name": "Postman expense xy",
    "paymentDate": "2021-10-01",
    "settlementId": "{{getSettlement.response.body.id}}",
    "payingParticipantId": "{{getSettlement.response.body.participants[0].id}}",
    "allocations": [
        {
            "participantId": "{{getSettlement.response.body.participants[0].id}}",
            "value": 100
        },
        {
            "participantId": "{{getSettlement.response.body.participants[1].id}}",
            "value": 50
        }
    ]
}

### 

# @name getExpenses
GET {{baseUrl}}/api/v1/settlements/{{getSettlement.response.body.id}}/expenses
Authorization: Bearer {{login.response.body.accessToken}}

###

# @name reimbursement
GET {{baseUrl}}/api/v1/settlements/{{getSettlement.response.body.id}}/reimbursement
Authorization: Bearer {{login.response.body.accessToken}}