# @name register
POST {{baseUrl}}/api/v1/users/register
Content-Type: application/json

{
    "email": "user2@example.com",
    "password": "user2",
    "nickname": "User2"
}

### 

# @name login
POST {{baseUrl}}/api/v1/users/login
Content-Type: application/json

{
    "email": "user2@example.com",
    "password": "user2"
}

###

# @name me
GET {{baseUrl}}/api/v1/users/me
Authorization: Bearer {{login.response.body.accessToken}}

###

# @name loginWrongPassword
POST {{baseUrl}}/api/v1/users/login
Content-Type: application/json

{
    "email": "testa@example.com",
    "password": "wrongpassword"
}
