version: "3.7"
services:
  api:
    image: registry.gitlab.com/tomejzen/expense-splitter/expense-splitter-api:production
    build:
      context: .
      dockerfile: ./ExpenseSplitter.Api/Dockerfile
    ports:
      - published: 7001
        target: 7001
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    networks:
      - proxy_public
    environment:
      - ENVIRONMENT=Production
      - ConnectionStrings__Context=${ConnectionStrings__Context}

networks:
  proxy_public:
    external: true
