version: "3.7"
services:
  web:
    image: registry.gitlab.com/tomejzen/expense-splitter/expense-splitter-web:development
    build:
      context: ./ExpenseSplitter.Web
      args:
        enviroment: development
    ports:
      - published: 7000
        target: 7000
    environment:
      - ENVIRONMENT=development
