version: "3.7"
services:
  web:
    image: registry.gitlab.com/tomejzen/expense-splitter/expense-splitter-web:production
    build:
      context: ./ExpenseSplitter.Web
      args:
        enviroment: production
    ports:
      - published: 7000
        target: 7000
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    networks:
      - proxy_public
    environment:
      - ENVIRONMENT=production

networks:
  proxy_public:
    external: true
