// <auto-generated />
using System;
using ExpenseSplitter.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ExpenseSplitter.Api.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20191217185303_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ExpenseSplitter.Api.Data.Expense", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("AdderId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(50) CHARACTER SET utf8mb4")
                        .HasMaxLength(50);

                    b.Property<DateTime>("PaidAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("PayerId")
                        .HasColumnType("int");

                    b.Property<string>("TripUid")
                        .HasColumnType("varchar(16) CHARACTER SET utf8mb4");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AdderId");

                    b.HasIndex("PayerId");

                    b.HasIndex("TripUid");

                    b.ToTable("Expenses");
                });

            modelBuilder.Entity("ExpenseSplitter.Api.Data.ExpensePart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("ExpenseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(12, 2)");

                    b.HasKey("Id");

                    b.HasIndex("ExpenseId");

                    b.ToTable("ExpensesParts");
                });

            modelBuilder.Entity("ExpenseSplitter.Api.Data.ExpensePartUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("ExpenseId")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ExpenseId");

                    b.HasIndex("UserId");

                    b.ToTable("ExpensesPartsUsers");
                });

            modelBuilder.Entity("ExpenseSplitter.Api.Data.Trip", b =>
                {
                    b.Property<string>("Uid")
                        .HasColumnType("varchar(16) CHARACTER SET utf8mb4")
                        .HasMaxLength(16);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("varchar(100) CHARACTER SET utf8mb4")
                        .HasMaxLength(100);

                    b.Property<string>("Name")
                        .HasColumnType("varchar(50) CHARACTER SET utf8mb4")
                        .HasMaxLength(50);

                    b.HasKey("Uid");

                    b.ToTable("Trips");
                });

            modelBuilder.Entity("ExpenseSplitter.Api.Data.TripUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(60) CHARACTER SET utf8mb4")
                        .HasMaxLength(60);

                    b.Property<string>("TripUid")
                        .HasColumnType("varchar(16) CHARACTER SET utf8mb4");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TripUid");

                    b.HasIndex("UserId");

                    b.ToTable("TripsUsers");
                });

            modelBuilder.Entity("ExpenseSplitter.Api.Data.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("varchar(50) CHARACTER SET utf8mb4")
                        .HasMaxLength(50);

                    b.Property<string>("Password")
                        .HasColumnType("varchar(100) CHARACTER SET utf8mb4")
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ExpenseSplitter.Api.Data.Expense", b =>
                {
                    b.HasOne("ExpenseSplitter.Api.Data.User", "Adder")
                        .WithMany()
                        .HasForeignKey("AdderId");

                    b.HasOne("ExpenseSplitter.Api.Data.User", "Payer")
                        .WithMany()
                        .HasForeignKey("PayerId");

                    b.HasOne("ExpenseSplitter.Api.Data.Trip", "Trip")
                        .WithMany()
                        .HasForeignKey("TripUid");
                });

            modelBuilder.Entity("ExpenseSplitter.Api.Data.ExpensePart", b =>
                {
                    b.HasOne("ExpenseSplitter.Api.Data.Expense", "Expense")
                        .WithMany()
                        .HasForeignKey("ExpenseId");
                });

            modelBuilder.Entity("ExpenseSplitter.Api.Data.ExpensePartUser", b =>
                {
                    b.HasOne("ExpenseSplitter.Api.Data.Expense", "Expense")
                        .WithMany()
                        .HasForeignKey("ExpenseId");

                    b.HasOne("ExpenseSplitter.Api.Data.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("ExpenseSplitter.Api.Data.TripUser", b =>
                {
                    b.HasOne("ExpenseSplitter.Api.Data.Trip", "Trip")
                        .WithMany()
                        .HasForeignKey("TripUid");

                    b.HasOne("ExpenseSplitter.Api.Data.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");
                });
#pragma warning restore 612, 618
        }
    }
}
