name: Continuous integration

on: [push]

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  scan:
    name: Scan
    uses: ./.github/workflows/workflow-scan.yml
    secrets: inherit

  test:
    name: Tests
    uses: ./.github/workflows/workflow-test.yml
    with:
      publish_coverage_history: ${{ github.ref == 'refs/heads/main' }}
    secrets: inherit

  version:
    name: Version
    uses: ./.github/workflows/workflow-version.yml

  build_scan:
    name: Docker image
    needs: [scan, test, version]
    uses: ./.github/workflows/workflow-docker-build-scan-push.yml
    with:
      image_name: rutkowski/expensesplitter-api
      enable_push: true
      build_context: src
      dockerfile: src/ExpenseSplitter.Api.Presentation/Dockerfile
      release_tag: ${{ needs.version.outputs.release_tag || 'latest' }}
    secrets: inherit
