name: CI/CD pipeline

on:
  push
  
permissions:
  contents: write

jobs:
  test:
    name: Unit tests
    uses: ./.github/workflows/workflow-test.yml

  tag_release:
    runs-on: ubuntu-latest
    steps:
      - name: Tag release
        id: my_tag_release
        uses: ./.github/workflows/workflow-tag-release.yml
      - name: Print release tag
        run: |
          echo "Release tag: ${{ steps.my_tag_release.outputs.release_tag }}"
    outputs:
      release_tag: ${{ steps.my_tag_release.outputs.release_tag }}

  print_tag_release:
    needs: [tag_release]
    runs-on: ubuntu-latest
    steps:
      - name: Print release tag
        run: |
          echo "Release tag 1: ${{ needs.tag_release.outputs.release_tag }}"

  build_scan:
    name: Docker image
    needs: [test, tag_release]
    uses: ./.github/workflows/workflow-docker-build-scan-push.yml
    with:
      image_name: rutkowski/expensesplitter-api
      enable_push: true
      build_context: src
      dockerfile: src/ExpenseSplitter.Api.Presentation/Dockerfile
      release_tag: ${{ needs.tag_release.outputs.release_tag }}
    secrets: inherit
