name: CI feature branch

on:
  push:
    branches-ignore:
      - main

permissions:
  contents: write

jobs:
  test:
    name: Unit tests
    uses: ./.github/workflows/workflow-test.yml

  build_scan:
    name: Docker image
    uses: ./.github/workflows/workflow-docker-build-scan-push.yml
    with:
      image_name: rutkowski/expensesplitter-api
      enable_push: false
      build_context: src
      dockerfile: ./ExpenseSplitter.Api.Presentation/Dockerfile
