name: CI feature branch

on:
  push:
    branches-ignore:
      - main

permissions:
  contents: write

jobs:
  test:
    name: Unit tests
    uses: ./.github/workflows/workflow-test.yml

  tag_release:
    name: Tag release
    # TODO: needs: test
    uses: ./.github/workflows/workflow-tag-release.yml

  build_scan:
    name: Docker image
    needs: tag_release
    uses: ./.github/workflows/workflow-docker-build-scan-push.yml
    with:
      image_name: rutkowski/expensesplitter-api
      enable_push: false
      build_context: src
      dockerfile: src/ExpenseSplitter.Api.Presentation/Dockerfile
      release_tag: ${{ needs.tag_release.outputs.release_tag }}
