name: CI/CD pipeline

on:
  push
  
permissions:
  contents: write

jobs:
  test:
    name: Unit tests
    uses: ./.github/workflows/workflow-test.yml

  tag_release:
    name: Tag release
    uses: ./.github/workflows/workflow-tag-release.yml

  print_release_tag:
    name: Print release tag
    runs-on: ubuntu-latest
    steps:
      - name: Printer
        run: |
          echo ${{ env.RELEASE_TAG }}

  build_scan:
    name: Docker image
    needs: [test, tag_release]
    uses: ./.github/workflows/workflow-docker-build-scan-push.yml
    with:
      image_name: rutkowski/expensesplitter-api
      enable_push: true
      build_context: src
      dockerfile: src/ExpenseSplitter.Api.Presentation/Dockerfile
      release_tag: ${{ env.RELEASE_TAG }}
    secrets: inherit
