name: CI/CD pipeline

on:
  push

permissions: write-all

jobs:
  test:
    name: Test
    uses: ./.github/workflows/workflow-test.yml
    with:
      publish_coverage: true

  tag_release:
    name: Tag release
    uses: ./.github/workflows/workflow-tag-release.yml

  build_scan:
    name: Docker image
    needs: [test, tag_release]
    uses: ./.github/workflows/workflow-docker-build-scan-push.yml
    with:
      image_name: rutkowski/expensesplitter-api
      enable_push: true
      build_context: src
      dockerfile: src/ExpenseSplitter.Api.Presentation/Dockerfile
      release_tag: ${{ needs.tag_release.outputs.release_tag }}
    secrets: inherit

