on:
  workflow_call:
    outputs:
      release_tag:
        description: "The generated semantic release tag"
        value: ${{ jobs.release.outputs.tag }}

permissions:
  contents: write

jobs:
  release:
    name: Semantic release tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Semantic Release
        id: semantic_release
        uses: cycjimmy/semantic-release-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          working_directory: semantic-release
          branches: |
            [
              "main",
              { 
                "name": "feature/*",
                "prerelease": "alpha"
              }
            ]
          extra_plugins: |
            @semantic-release/changelog@6.0.3
            @semantic-release/commit-analyzer@9.0.2
            @semantic-release/github@8.0.7
            conventional-changelog-conventionalcommits@6.1.0
          extends: conventional-changelog-conventionalcommits@6.1.0

    outputs:
      tag: ${{ steps.semantic_release.outputs.new_release_version }}
