on:
  workflow_call:

permissions:
  contents: write

jobs:
  release:
    name: Semantic release tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          working_directory: semantic-release
          branches: |
            [
              "main",
              { 
                "name": "feature/*",
                "prerelease": "alpha"
              }
            ]
          extra_plugins: |
            @semantic-release/changelog@6.0.3
            @semantic-release/commit-analyzer@9.0.2
            @semantic-release/github@8.0.7
            conventional-changelog-conventionalcommits@6.1.0
          extends: conventional-changelog-conventionalcommits@6.1.0

      - name: Output release tag
        run: echo "release_tag=$(git describe --tags)" >> $GITHUB_ENV

    outputs:
      release_tag: ${{ env.release_tag }}
