on:
  workflow_call:
    outputs:
      release_tag:
        description: "The generated semantic release tag"
        value: ${{ jobs.release.outputs.release_tag }}

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  release:
    name: Semantic release tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Semantic Release
        if: ${{ github.ref == 'refs/heads/main' }}
        id: semantic_release
        uses: cycjimmy/semantic-release-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          working_directory: semantic-release
        continue-on-error: true

    outputs:
      release_tag: ${{ steps.semantic_release.outputs.new_release_version || format('alpha-{0}', github.sha) }}
