on:
  workflow_call:
    inputs:
      publish_coverage_history:
        type: boolean
        default: false

permissions:
  contents: read

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore coverage history
        uses: dawidd6/action-download-artifact@v6
        if: ${{ inputs.publish_coverage_history }}
        with:
          name: CoverageHistory
          path: CoverageHistory
          github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        continue-on-error: true

      - name: Test with the dotnet CLI
        run: dotnet test --collect:"XPlat Code Coverage" *.sln

      - name: ReportGenerator
        uses: danielpalme/ReportGenerator-GitHub-Action@5
        with:
          reports: 'test/*Test*/TestResults/*/coverage.cobertura.xml'
          targetdir: 'CoverageReports'
          historydir: 'CoverageHistory'
          reporttypes: 'HtmlInline;Cobertura;MarkdownSummaryGithub'
          filefilters: '-*/Migrations/*'

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: CoverageReports
          path: CoverageReports

      - name: Upload coverage history
        if: ${{ inputs.publish_coverage_history }}
        uses: actions/upload-artifact@v4
        with:
          name: CoverageHistory
          path: CoverageHistory

      - name: Add comment to PR
        if: github.event_name == 'pull_request'
        run: gh pr comment $PR_NUMBER --body-file CoverageReports/SummaryGithub.md
        env:
          GH_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          PR_NUMBER: ${{ github.event.number }}

      - name: Publish coverage in build summary
        run: cat CoverageReports/SummaryGithub.md >> $GITHUB_STEP_SUMMARY
