on:
  workflow_call:
    outputs:
      release_tag:
        description: "The generated semantic release tag"
        value: ${{ jobs.release.outputs.release_tag }}

permissions: write-all

jobs:
  release:
    name: Semantic release tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Semantic Release
        id: semantic_release
        uses: cycjimmy/semantic-release-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_format: v${version}
          extra_plugins: |
            "@semantic-release/commit-analyzer",
            [
              "@semantic-release/github",
              {
                "successComment": false,
                "failTitle": false
              }
            ]
          branches: |
            [
              "main",
              { 
                "name": "feature/*",
                "prerelease": "alpha"
              }
            ]

    outputs:
      release_tag: ${{ steps.semantic_release.outputs.new_release_version }}
