on:
  workflow_call:
    outputs:
      release_tag:
        description: "The generated semantic release tag"
        value: ${{ jobs.release.outputs.release_tag }}

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  release:
    name: Semantic release tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Bump version and push git tag
        id: version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create a GitHub release
        if: github.ref == 'refs/heads/main'
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.version.outputs.new_tag }}
          name: ${{ steps.version.outputs.new_tag }}
          body: ${{ steps.version.outputs.changelog }}

      - name: Generate build summary
        run: |
          echo "🏷️ Version: ${{ steps.version.outputs.new_version }}" >> $GITHUB_STEP_SUMMARY
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "📌 Release Tag: ${{ steps.version.outputs.new_tag }}" >> $GITHUB_STEP_SUMMARY
          fi
          
    outputs:
      release_tag: ${{ steps.version.outputs.new_tag }}
