on:
  workflow_call:
    inputs:
      publish_coverage:
        type: boolean
        default: false

permissions:
  contents: write

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Test with the dotnet CLI
        run: dotnet test --collect:"XPlat Code Coverage" *.sln

      - name: Restore coverage history
        if: ${{ inputs.publish_coverage }}
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          name: CoverageHistory
          path: CoverageHistory
          if_no_artifact_found: warn

      - name: ReportGenerator
        if: ${{ inputs.publish_coverage }}
        uses: danielpalme/ReportGenerator-GitHub-Action@5
        with:
          reports: 'test/*Test*/TestResults/*/coverage.cobertura.xml'
          targetdir: 'CoverageReports'
          historydir: 'CoverageHistory'
          reporttypes: 'HtmlInline;Cobertura'
          filefilters: '-*/Migrations/*'

      - name: Upload coverage report
        if: ${{ inputs.publish_coverage }}
        uses: actions/upload-artifact@v4
        with:
          name: CoverageReports
          path: CoverageReports

      - name: Upload coverage history
        if: ${{ inputs.publish_coverage }}
        uses: actions/upload-artifact@v4
        with:
          name: CoverageHistory
          path: CoverageHistory
          